#+TITLE: La lucha de facciones
#+PUBLISHED: true
#+PERMALINK: la%20lucha%20de%20facciones
#+PUBLIC: true

** *Gerardo Duarte Vargas*
** -----------------------------------------------------------------------------------------
** Fue una guerra entre los convencionistas -formado por villistas y zapatistas- y los constitucionalistas -formado por los carrancistas y sus allegados- Ambos bandos buscaban tomar el poder del país, pero con ideas distintas cada uno.  Tras una serie de problemas que atravesaban los carrancistas, los villistas y zapatistas aprovecharon para tomar territorios y poder sobre sus rivales, logrando controlar el suministro de armas y posiciones estratégicas gracias a su ya mencionada ventaja territorial pero también numérica en tropas. Por su parte, los carrancistas se encontraban desplegados por las zonas costeras e incomunicados entre sí, pero con una ventaja económica importante proveniente de los ingresos de la industria petrolera, aduanas y exportación de ((6036de34-9d87-4c75-9805-f83d40d62ae8)) . Sumando también el apoyo militar norteamericano, lo que limitó las armas conseguidas por el ejército villista. Fuera de estos valores encontrados y agregados, los carrancistas tenían un valor intrínseco muy grande; su unidad, el tener un solo líder. Aunque esto a su vez tenía otro valor agregado, el conocimiento sobre el Estado y su gobernación gracias a su "Jefe Máximo", Venustiano Carranza. Cuando los convencionistas tuvieron la oportunidad de acabar con los constitucionalistas, aún con todo y sus ventajas, Villa decidió no ir tras Carranza y hacerlo huir vía marítima, situación que les causaría problemas en un futuro cercano. Paulatinamente los carrancistas pudieron reorganizarse y lograron quitar territorios a los villistas y zapatistas, quienes estaban más preocupados por sus regiones que por el establecimiento real de un gobierno. Pero, ¿cuáles se pueden considerar los motivos que llevaron a esta lucha de facciones? Podemos considerar en primera instancia la búsqueda de este poder que tanto se habla para poder conseguir el cumplimiento de sus demandas por parte de ambos bandos. Esto se puede ver en, por ejemplo, las posiciones frente a la relación Iglesia-Estado, donde los carrancistas iban en contra de la iglesia y los villistas las apoyaban y protegían. También se puede ver en el tema agrario, donde otra vez vemos esta dicotomía en sus posturas y opiniones. Los villistas -menos que los zapatistas- buscaban la repartición agraria, mientras que los carrancistas -aunque no todos- lo veían contraproducente. En la recta final de la guerra de facciones Álvaro Obregón con su gran experiencia militar logro tomar varias ciudades de regreso para los carrancistas. Agregaron en el Plan de Ayala, prometiendo leyes a favor del pueblo. Finalmente se derrotó a Villa, pudiendo así tomar el control de la mayoría del territorio nacional. Consiguiendo apoyo de norteamerica, con el reconocimiento de la ventaja militar del Obregón y logrando finalmente derrotar a Villa en 1919.