#+TITLE: La Revolución Mexicana

** Tras años de dictadura en México con Díaz al frente de esta, el país necesitaba una renovación en su estructura política. Madero fue el principal impulsor de la idea de una renovación, una idea de democracia real, sin influencias en las decisiones y sin violaciones a esta misma democracia. Esto se evidenciaba en el libro que Madero escribió /La sucesión presidencial de 1910/. Fue entonces cuando Madero decidido a realizar este cambio y quitar a Díaz del poder crea el Partido Nacional Antirreeleccionista. Al movimiento de Madero se unieron los "reyistas", inconformes por el apoyo a los "científicos" que el gobierno de Díaz les brindó. Paulatinamente más personas fueron sumándose a dicho movimiento, entre ellos también las personas del pueblo que trabajaban en las tierras, los llamados "campesinos", quienes buscaban la repartición de tierras después de ser omitidos en el gobierno de Díaz. No todo el trayecto de Madero fue triunfal. En 1910 Madero fue encarcelado en San Luis Potosí por incitar a rebeliones, cerca de las elecciones, para evitar su participación en ellas, elecciones que fueron ganadas por Díaz de nueva cuenta. En noviembre del mismo año Madero es puesto en libertad y huye a San Antonio, Texas. En Texas Madero redacta él ((6036de34-7b00-4ea4-be94-c4e96383ebe9)), el cual fue firmado el 5 de octubre de 1910. En el Plan de San Luis se llamaba al pueblo a realizar una revolución no violenta -para evitar intervenciones extranjeras- el 20 de noviembre de 1910, esto para establecer una democracia electoral, limitar los derechos de los extranjeros y devolver tierras injustamente expropiadas a los pueblos -algo que parecía en un principio no ser tomado en cuenta por Madero-
La revolución incitada por Madero fue cesada casi por completo, incluyendo la muerte de Álvaro Obregón. Todos los estados tenían miedo de Díaz y sus fuerzas, por lo que no actuaban. El movimiento del Estado de Chihuahua fue el primero en iniciar, de manera fuerte y real, una lucha. Chihuahua era un estado que podía otorgar grupos fuertes y experimentados que pusieran en problemas a los militares, no en vano habían pasado años combatiendo a quienes rivalizaran con ellos. Un ejemplo de la fortaleza de Chihuahua es el ejército de Pascual Orozco, quien era un destacado militar de aquel estado, y Doroteo Arango, mejor conocido como Pancho Villa, quien fue el único combatiente de clase baja que se destacó. El 14 de febrero de 1911 Madero llega a Chihuahua con la protección de los guerrilleros del lugar, expandiendo e incrementando la fuerza del movimiento que él había iniciado y dando paso a nuevos líderes como los ya antes mencionados en Chihuahua y otros como Emiliano Zapata en Morelos. Gracias a la fuerza que sumaba la revolución el hermano de Francisco Madero, Gustavo Madero, logró junto con un abogado estadounidense ganar el apoyo de la gente de Estados Unidos.
