#+TITLE: LyE1: Reseña - Romper el silencio

** Este libro recopila escritos de diversa autoría de sucesos de periodistas en el país que temen y corren riesgos al cubrir notas que de alguna manera perjudican los intereses de grupos delictivos, el famoso /narco/, grupos que pretenden manipular a su beneficio los medios de difusión. Riesgos que no deberían existir para estos periodistas -ni nadie- pero lo hacen. Estos textos exponen aquellos atentados contra dichos periodistas, aquella desprotección y desinterés por estas personas.
** Para efectos de esta reseña cubriremos el texto /Tres formas de aprender el silencio/ de Carlos Manuel Juárez. Quien relata la historia de Ramiro Treviño, un fotorreportero de Tamaulipas cuya labor es cubrir notas policiacas. Dichas notas empezaron con un espacio limitado dentro del periódico en el que laboraba. Poco a poco se le otorgó más espacio y titularidad a las notas de Treviño, llamadas "Punto rojo". Notas que seguían la fórmula que siempre caracterizo a Treviño, la de exponer noticias policiacas y de crimen organizado que tanto se venían suscitando en la frontera del país, de exponer cifras, datos, nombres de personas y lugares de los hechos. La fórmula del éxito, pero también la fórmula para ganarse /narcoenemigos/. Era de esperar que a dichos criminales no les gustaría que fueran expuestos y señalados en ningún periódico. Motivo que llevó a un grupo de criminales, vendedores de droga al mayoreo, los llamados /grameros/, a citar a Treviño para ser amenazado con su silencio a cambio de dinero o de un balazo. Con el tiempo dichas amenazas llevaron a Treviño al punto más álgido en cuanto amenazas y careos con el /narco/ se refiere. Una navidad el periodista fue sustraído y llevado a una casa de control del jefe de los mafiosos. Fue golpeado, pateado, amenazado y cuestionado. Sintió el miedo por su vida, el pavor. Después de esta ocasión, tras haber vivido muchas similares antes, decidió por fin, no mover un dedo, no modificar nada. Treviño decidió su vida frente a la verdad periodística.
** /Tres formas de aprender el silencio/ es un texto que sin tapujos te enseña la realidad que viven los periodistas. Un texto que no escatima en detalles, que tampoco se ahorra palabras que pueden quitarle formalidad al mismo. Pero que no le quita peso ni fuerza, pues su función es la de informar y sobre todo /crear conciencia/ de una situación real que le ocurre a aquella gente que solo hace su trabajo informando al resto del país. Me parece logra de manera acertada su cometido y que ha sido motivo de toma de acciones, llegando incluso a oídos de la /CNDH/.