#+TITLE: MEPS1: 7ma tarea

** IN-PROGRESS _Continúa el ejercicio de ir colocando en orden los eventos. Puedes hacerlo completando la misma cronología anterior, con los acontecimientos, planes, etc. que surjan._
:PROPERTIES:
:in-progress: 1614124509810
:END:
*** ^^La lista completa de fechas se encuentra en: *[[MEPS1: Fechas de 6ª y 7ª tarea]]*^^ #kanban-w200
**** *1913*
***** /Plan de Guadalupe/.
***** Huerta disuelve el Congreso.
***** Huerta arresta a diputados hostiles para su régimen.
***** Huerta convoca a elecciones de diputación.
***** Félix Díaz huye del país en un buque estadounidense.
***** Amenaza Wilson a Huerta con apoyar a Constitucionalistas sin no dimitía.
***** Huerta busca apoyo en la iglesia católica.
***** La / Asociación Católica de la Juventud Mexicana/ toma fuerza y acción en los asuntos civiles.
**** *1914*
***** Toma de la plaza Zacateneca.
***** Toma de Culiacán, Nayarit y Jalisco.
***** Pablo González toma ciudades del sur.
***** Los Zapatistas toman Milpa Alta.
***** Detienen a marineros estadounidenses y Wilson emprende intervención contra Huerta.
***** Wilson y Estado Unidos toman el puerto de Veracruz.
***** Huerta obtiene del Congreso poderes dictatoriales y movilizó manifestaciones patrióticas.
***** Huerta dimite.
***** Los huertistas firman la paz.
***** Las tropas de Obregón ocupan la capital.
***** Carranza instala su gobierno en el Palacio Nacional.
***** Carranza y Villa bloquean la llegada de los zapatistas a la capital.
***** La Soberana Convención de Aguascalientes se celebra para decidir como administrar el poder.
***** Se llega a una resolución con los zapatistas por parte de Felipe Ángeles.
***** Llegan los zapatistas a la Convención y piden la adhesión del /Plan de Ayala/.
***** Un tercer grupo formado por la División del Norte y grupos independientes asumieron el liderazgo.
***** La Convención nombra a Eulalio Gutiérrez presidente interino.
***** Carranza envía una carta, leída por Obregón, marcó la ruptura con Villa.
***** Villa se convierte en jefe del ejército convencionista.
***** Los ejércitos de Villa y  Zapata llegan a la Ciudad de México.
***** Se hacen adiciones al /Plan de Ayala/.
**** *1915*
***** Álvaro Obregón retoma Puebla.
***** Se comienza la /Ley Agraria/.
***** Las empresas petroleras suspenden labores hasta la revisión de la legislación.
***** Obregón y Villa se enfrentan, saliendo Obregón victorioso.
***** Wilson reconoce el gobierno de Carranza.
***** Escasez de alimentos.
***** Aumento de la inflación.
***** Huelgas para recuperar el poder adquisitivo.
**** *1916*
***** Huelgas para exigir pago en monedas de oro.
***** Dejan de circular billetes en el país.
**** *1917*
***** Entra la primera Guerra Mundial.
***** Estados Unidos prohíbe la exportación de cereales a México.
**** *1918*
***** La epidemia de gripe española golpea a México.
** DONE _Explica con tus palabras la guerra de facciones._
:PROPERTIES:
:in-progress: 1614134952584
:done: 1614197918322
:END:
*** [[La lucha de facciones]] fue una guerra entre los convencionistas -formado por villistas y zapatistas- y los constitucionalistas -formado por los carrancistas y sus allegados- Ambos bandos buscaban tomar el poder del país, pero con ideas distintas cada uno. Podemos considerar como motivos e ideas en primera instancia la búsqueda de este poder que tanto se habla para poder conseguir el cumplimiento de sus demandas por parte de ambos bandos. Esto se puede ver en, por ejemplo, las posiciones frente a la relación Iglesia-Estado, donde los carrancistas iban en contra de la iglesia y los villistas las apoyaban y protegían. También se puede ver en el tema agrario, donde otra vez vemos esta dicotomía en sus posturas y opiniones. Los villistas -menos que los zapatistas- buscaban la repartición agraria, mientras que los carrancistas -aunque no todos- lo veían contraproducente. Fue una lucha de altas y bajas, donde cada uno tuvo ciertas ventajas y desventajas. En términos generales podemos decir que en cierto punto los villistas y zapatistas tuvieron una mayor ventaja frente a los carrancistas, pero que no supieron aprovechar pues pronto perderían el control de los territorios, su ventaja militar y táctica. Este conflicto culminaría con una asombrosa campaña militar por parte de Álvaro Obregón y una toma de poder definitiva por parte de Carranza.
** DONE _Destaca y explica los artículos que se mencionan como los más significativos de la Constitución de 1917._
:PROPERTIES:
:in-progress: 1614219469506
:done: 1614220301936
:END:
*** *Artículo 27*
**** Los recursos naturales se volvían propiedad de la nación.
**** Limitaba el derecho de los extranjeros y asociaciones religiosas para adquirir tierras.
**** Restitución de todas las tierras enajenadas a los pueblos con base en las Leyes de Reforma, y el otorgamiento de tierras a pueblos sin parcelas.
**** Fue la base para la reforma agraria y nacionalización del petróleo.
*** *Artículo 123*
**** Otorgaba derechos fundamentales a trabajadores.
***** Jornada laboral máxima de ocho horas.
***** Descanso semanal.
***** Salario mínimo.
**** Definía normas sobre bienestar social.
***** Trabajo prohibido para menores de doce años.
**** Reconocía derechos colectivos.
***** Formación de sindicatos y huelga.
***** Formación de /Juntas de Conciliación y Arbitraje/ para resolucion de conflictos.
*** *Artículo 3*
**** Establecía la laicidad de las escuelas, sujetándose a vigilancia oficial.
**** También la gratuidad  de la escuela a nivel básico impartida por el Estado.
**** Prohibía las fundaciones de escuelas primarias por parte de la iglesia.
** IN-PROGRESS _Haz un resumen CON TUS PALABRAS, en una cuartilla (una página a espacio y medio en Word) sobre TODA LA LECTURA. De manera que expliques lo que comprendiste del proceso de la Revolución._
:PROPERTIES:
:in-progress: 1614277814652
:END:
*** Tras años de dictadura en México con Díaz al frente de esta, el país necesitaba una renovación en su estructura política. Madero fue el principal impulsor de la idea de una renovación, una idea de democracia real, sin influencias en las decisiones y sin violaciones a esta misma democracia. Esto se evidenciaba en el libro que Madero escribió /La sucesión presidencial de 1910/. Fue entonces cuando Madero decidido a realizar este cambio y quitar a Díaz del poder crea el Partido Nacional Antirreeleccionista. Al movimiento de Madero se unieron los "reyistas", inconformes por el apoyo a los "científicos" que el gobierno de Díaz les brindó. Paulatinamente más personas fueron sumándose a dicho movimiento, entre ellos también las personas del pueblo que trabajaban en las tierras, los llamados "campesinos", quienes buscaban la repartición de tierras después de ser omitidos en el gobierno de Díaz. No todo el trayecto de Madero fue triunfal. En 1910 Madero fue encarcelado en San Luis Potosí por incitar a rebeliones, cerca de las elecciones, para evitar su participación en ellas, elecciones que fueron ganadas por Díaz de nueva cuenta. En noviembre del mismo año Madero es puesto en libertad y huye a San Antonio, Texas. En Texas Madero redacta él ((6036de34-7b00-4ea4-be94-c4e96383ebe9)), el cual fue firmado el 5 de octubre de 1910. En el Plan de San Luis se llamaba al pueblo a realizar una revolución no violenta -para evitar intervenciones extranjeras- el 20 de noviembre de 1910, esto para establecer una democracia electoral, limitar los derechos de los extranjeros y devolver tierras injustamente expropiadas a los pueblos -algo que parecía en un principio no ser tomado en cuenta por Madero-
La revolución incitada por Madero fue cesada casi por completo, incluyendo la muerte de Álvaro Obregón. Todos los estados tenían miedo de Díaz y sus fuerzas, por lo que no actuaban. El movimiento del Estado de Chihuahua fue el primero en iniciar, de manera fuerte y real, una lucha. El 14 de febrero de 1911 Madero llega a Chihuahua con la protección de los guerrilleros del lugar, expandiendo e incrementando la fuerza del movimiento que él había iniciado y dando paso a nuevos líderes como Pascual Orozco, Pancho Villa y otros como Emiliano Zapata en Morelos. Gracias a la fuerza que sumaba la revolución el hermano de Francisco Madero, Gustavo Madero, logró junto con un abogado estadounidense ganar el apoyo de la gente de Estados Unidos. En mayo de dicho año Orozco y Villa toman Ciudad Juárez, lo que casi ponía fin al gobierno de Díaz. Madero decidió negociar con Díaz, firmando el ((60382219-e919-4a12-96da-2da7229eee4e)) donde se establece la renuncia de Díaz a la presidencia y el fin de la rebelión. Díaz abandonó el país y en su lugar quedó un presidente de transición. En junio de 1911 Madero regresa a la Ciudad de México como ídolo, pero tras su llegada parecían solo encontrar problemas.
